name: Bug Report
description: File a bug report
title: ""
labels: ["bug"]
assignees:

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
      attributes:
        label: Contact Details
        description: How can we get in touch with you if we need more info? (This is completely optional)
        placeholder: ex. discord_username#1234
      validations:
        required: false
  - type: textarea
    id: what-happened
      attributes:
        label: What happened?
        description: Also tell us, what did you expect to happen?
        placeholder: Tell us what you see! You can also upload files (like screenshots) by dragging them into this text area.
    validations:
      required: true
  - type: dropdown
    id: version
      attributes:
        label: Version
        description: What version of our software are you running?
        options: 
          - latest (Default)
      validations:
        required: true
