name: Push to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  push:
    name: Push to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.STAGING_PATH }}
            git pull
            npm install pm2@latest -g
            pm2 restart modrunner-staging
